# Experimental docker-compose for local use. Access `web` at localhost:30100.

version: "3.7"

services:
    db:
        image: postgres:12.8-alpine
        volumes:
            - type: bind
              source: ./local_data
              target: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - .env.postgres.local
    redis:
        image: redis:6.2
    cron:
        build:
            context: .
            args:
                env: dev
                target: aws
        entrypoint: docker-php-entrypoint
        command: /var/www/html/deploy/task_entrypoint.sh
        volumes:
            - .:/var/www/html
        env_file:
            - .env.local
        depends_on:
            - db
            - redis
    web:
        build:
            context: .
            args:
                env: dev
                target: aws
        ports:
            - "30100:8080"
        volumes:
            - .:/var/www/html
        env_file:
            - .env.local
        depends_on:
            - db
            - redis
    adminer:
        image: adminer
        ports:
            - "30101:8080"
