# Server and project configuration
sonar.host.url=https://sonar.wpengine.io/
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

# Project identifiers
sonar.projectName=wpackagist
sonar.projectKey=wpengine_wpackagist_82f90787-67b8-45bc-8b47-99fbcfb1c1e7

# Language
sonar.language=php

# Paths to source code directories (relative paths)
sonar.sources=src

# Exclusions
sonar.exclusions=**/*_test.*, **/mocks/**, **/node_modules/**, **/vendor/**

# Paths to test code directories (relative paths)
sonar.tests=.
sonar.test.inclusions=**/*Test.php

# Public repo: disable PR decoration to limit exposure of internal project details
sonar.pullrequest.github.summary.comment=false
